### ISSUE TITLE
Mousewheelie coflicting with Applied Energistics 

### ISSUE THREAD

**Issue by Bleuz** [TeamAOF/All-of-Fabric-3#131]
Running: Ubuntu Server 18.04 "Bionic Beaver" LTS (64bits)

During server startup this error appears in console.

 - Mod mousewheelie conflicts with mod {appliedenergistics2 @ [*]}, but the conflicting version is present: 8.1.0-alpha.10!

Completes Loaded 1/1 KubeJS startup scripts in 85.22 ms
Then proceeds to throw the following errors. Removing mousewheelie fixes the issues and allow server to start.

```
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_265]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_265]
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[fabric-server-launch.jar:?]
... 19 more
Caused by: java.lang.RuntimeException: Cannot load class de.siphalor.mousewheelie.client.inventory.sort.SortMode in environment type SERVER
at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:76) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:152) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148) ~[fabric-server-launch.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
at de.siphalor.mousewheelie.client.Config$Sort.<init>(Config.java:57) ~[mousewheelie-1.5.5+mc1.16.2-pre1.jar:?]
at de.siphalor.mousewheelie.client.Config.<init>(Config.java:53) ~[mousewheelie-1.5.5+mc1.16.2-pre1.jar:?]
at de.siphalor.mousewheelie.MouseWheelie.<clinit>(MouseWheelie.java:13) ~[mousewheelie-1.5.5+mc1.16.2-pre1.jar:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_265]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_265]
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[fabric-server-launch.jar:?]
at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[fabric-server-launch.jar:?]
... 19 more
```

**Comment by Bleuz** [comment]
Ignore me. Realized it's a client side mod that shouldn't exist. How it got there... Not really sure
