### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by twothe** [TeamAOF/All-of-Fabric-3#261]
I just downloaded the latest version 2.5.6 from the CurseForge launcher (first time install) and started it, but the game is unable to launch. After a few seconds I get a crash:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'dishes'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/692331943.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2700$class_4297
		at zabi.minecraft.extraalchemy.statuseffect.ModEffectRegistry.<clinit>(ModEffectRegistry.java:29)
		at zabi.minecraft.extraalchemy.ExtraAlchemy.onInitialize(ExtraAlchemy.java:15)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2946/1974568676.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 24 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2700$class_4297
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 28 more
Caused by: java.lang.NoSuchFieldError: field_11153
	at eu.midnightdust.motschen.dishes.world.SaltOre.initBiomeFeatures(SaltOre.java:20)
	at eu.midnightdust.motschen.dishes.DishesMain.onInitialize(DishesMain.java:108)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2946/1974568676.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 24 more
```

**Comment by kabadesu** [comment]
That's odd, I don't think delicious dishes is in the pack? Can you try using GDlauncher instead of the curseforge launcher (there have been some issues with curseforge launcher lately)?

**Comment by Monster-Zer0** [comment]
This is over a month old and still no reply. changing to pending close.
