### ISSUE TITLE
v2.6.4 Crash when dying to mobs

### ISSUE THREAD

**Issue by thomaspendock** [TeamAOF/All-of-Fabric-3#288]
I died to a guardian and then zombie in a LAN world: crash in both cases.

```
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.class_1661.handler$ccd000$removeInvStack(class_1661.java:3699)
	at net.minecraft.class_1661.method_5447(class_1661.java)
	at net.minecraft.class_1309.handler$zpb000$dropHead(class_1309.java:24390)
	at net.minecraft.class_1309.method_16080(class_1309.java)
	at net.minecraft.class_3222.method_6078(class_3222.java:540)
	at net.minecraft.class_1309.method_5643(class_1309.java:1106)
	at net.minecraft.class_1657.method_5643(class_1657.java:914)
	at net.minecraft.class_3222.method_5643(class_3222.java:631)
	at net.minecraft.class_1577$class_1578.method_6268(class_1577.java:455)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at net.minecraft.class_1355.tickGoals(class_1355.java:1149)
	at net.minecraft.class_1355.method_6275(class_1355.java:1056)
	at net.minecraft.class_1308.method_6023(class_1308.java:736)
	at net.minecraft.class_1309.method_6007(class_1309.java:2508)
	at net.minecraft.class_1308.method_6007(class_1308.java:542)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1577.method_6007(class_1577.java:302)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_3218$$Lambda$10871/747267251.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$10372/1602931940.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1661.handler$ccd000$removeInvStack(class_1661.java:3699)
	at net.minecraft.class_1661.method_5447(class_1661.java)
	at net.minecraft.class_1309.handler$zpb000$dropHead(class_1309.java:24390)
	at net.minecraft.class_1309.method_16080(class_1309.java)
	at net.minecraft.class_3222.method_6078(class_3222.java:540)
	at net.minecraft.class_1309.method_5643(class_1309.java:1106)
	at net.minecraft.class_1657.method_5643(class_1657.java:914)
	at net.minecraft.class_3222.method_5643(class_3222.java:631)
	at net.minecraft.class_1577$class_1578.method_6268(class_1577.java:455)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at net.minecraft.class_1355.tickGoals(class_1355.java:1149)
	at net.minecraft.class_1355.method_6275(class_1355.java:1056)
	at net.minecraft.class_1308.method_6023(class_1308.java:736)
	at net.minecraft.class_1309.method_6007(class_1309.java:2508)
	at net.minecraft.class_1308.method_6007(class_1308.java:542)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1577.method_6007(class_1577.java:302)
	at net.minecraft.class_1309.method_5773(class_1309.java:2254)
	at net.minecraft.class_1308.method_5773(class_1308.java:342)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_3218$$Lambda$10871/747267251.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:guardian (net.minecraft.class_1577)
	Entity ID: 24692
	Entity Name: Guardian
	Entity's Exact location: 12.68, 79.00, 70.80
	Entity's Block location: World: (12,79,70), Chunk: (at 12,4,6 in 0,4; contains blocks 0,0,64 to 15,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 2 total; [class_3222['aussiewombat'/99, l='ServerLevel[AOF]', x=7.86, y=72.00, z=77.26], class_3222['ekgarrison00'/2244, l='ServerLevel[AOF]', x=8.78, y=81.25, z=79.01]]
	Chunk stats: ServerChunkCache: 2514
	Level dimension: minecraft:overworld
	Level spawn location: World: (-96,66,112), Chunk: (at 0,4,0 in -6,7; contains blocks -96,0,112 to -81,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 341681 game time, 559001 day time
	Level name: AOF
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 52956 (now: false), thunder time: 78215 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$10372/1602931940.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ImAK9** [comment]
Fixed in 2.6.5
https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3/files/3204728
