### ISSUE TITLE
Crash after making Makeshift, radius of 10

### ISSUE THREAD

**Issue by szumaster** [TeamAOF/All-of-Fabric-3#297]
after making cuboid (get of my lawn), and add myself as a owner, my friend teleport to me and he click on the stuff, after click on the chest, server crashed.

Heres log:

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2/20/21 9:29 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/therandomlabs/vanilladeathchest/util/DeathChestBlockEntity
	at draylar.goml.api.compat.DeathChestsCompat.lambda$register$0(DeathChestsCompat.java:19)
	at draylar.goml.EventHandlers.testPermission(EventHandlers.java:96)
	at draylar.goml.EventHandlers.lambda$registerInteractBlockCallback$2(EventHandlers.java:58)
	at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41)
	at net.minecraft.class_3225.handler$zii000$interactBlock(class_3225.java:2570)
	at net.minecraft.class_3225.method_14262(class_3225.java)
	at net.minecraft.class_3244.method_12046(class_3244.java:1040)
	at net.minecraft.class_2885.method_12547(class_2885.java:36)
	at net.minecraft.class_2885.method_11054(class_2885.java:10)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.therandomlabs.vanilladeathchest.util.DeathChestBlockEntity
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-52-generic
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 308697800 bytes (294 MB) / 2790260736 bytes (2661 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 2
	JVM Flags: 7 total; -Xms256M -Xmx8192M -XX:MinHeapFreeRatio=2 -XX:MaxHeapFreeRatio=7 -XX:ParallelGCThreads=2 -XX:CICompilerCount=2 -XX:ActiveProcessorCount=2
	Fabric Mods: 
		addendum: Addendum 1.16.5-1.0.2
		adorn: Adorn 1.13.0+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advdebug: Advancements Debug 2.2.0
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		appliedenergistics2: Applied Energistics 2 8.1.0-alpha.13
		architectury: Architectury 1.7.117
		artifacts: Artifacts 2.3.0+fabric
		artifice: Artifice 0.14.6+1.16.5
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		attributefix: Attribute Fix {FABRIC} 1.0.1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bambootweaks: Bamboo Tweaks unspecified
		battletowers: Battle Towers 3.3.2-1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.9.1-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betterthanmending: BetterThanMending 1.2.0
		biome_locator: Biome Locator 1.1.2
		biomemakeover: Biome Makeover 1.16.4-1.2.11
		blast: BLAST 1.5
		blockshifter: Blockshifter 1.3.2+fabric-1.16.4
		blockus: Blockus 2.0.2+1.16.4
		blue_endless_jankson: jankson 1.2.0
		byg: BYG 1.1.5
		campanion: Campanion 1.3.4
		cardinal-components: Cardinal Components API 2.7.12
		cardinal-components-base: Cardinal Components API (base) 2.7.12
		cardinal-components-block: Cardinal Components API (blocks) 2.7.12
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.12
		cardinal-components-entity: Cardinal Components API (entities) 2.7.12
		cardinal-components-item: Cardinal Components API (items) 2.7.12
		cardinal-components-level: Cardinal Components API (world saves) 2.7.12
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.12
		cardinal-components-util: Cardinal Components API (utilities) 2.7.12
		cardinal-components-world: Cardinal Components API (worlds) 2.7.12
		carrier: Carrier 1.7.4
		cavebiomes: Cave Biomes 0.6.2
		chainmail: Chainmail 0.5.0
		charm: Charm 2.2.2
		charmonium: Charmonium 2.2.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.3
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.10.13
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_nathanpb_safer: Safer 1.1.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compressedblocks: Compressed Blocks 1.0
		computercraft: CC:T for Fabric 1.91.2
		controlling: Controlling For Fabric 1.1.2
		couplings: Couplings 1.3.3
		crookedcrooks: Crooked Crooks 1.3.3+1.16.4
		croptopia: Croptopia 1.2.0
		croptosis: Croptosis 1.0.1
		crowdin-translate: CrowdinTranslate 1.2
		crusade: Crusade 1.2.0
		dankstorage: Dank Storage 1.9a-1.16.3
		darkpaintings: Dark Paintings 3.0.1
		dawn: Dawn API 1.6.5
		decimal_coins: Decimal Coins 1.16.2-1.2.0
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.3.1-beta5
		dwarfcoal: Dwarf Coal 1.16.2-1.0.0
		ecotones: Ecotones 0.7.1
		enchantmentdescriptions: Enchantment Descriptions 2.0.1
		expandedstorage: ExpandedStorage 5.6.32
		ezpas: Ezpas 1.2.3-1.16.2
		fabric: Fabric API 0.30.3+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric Api Lookup API (v1) 1.0.0+8f91dfb63a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-language-scala: Fabric Language Scala 1.0.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		fallflyinglib: FallFlyingLib 1.1.0
		fasttransferlib: Fast Transfer Lib 0.2.2
		fatxporbs: Fat Experience Orbs 0.0.9
		fermion: Fermion 2.9.218
		fermion-gui: Fermion GUI 2.5.218
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		fermion-orientation: Fermion Orientation 1.2.218
		fermion-simulator: Fermion Simulator 1.8.218
		fermion-varia: Fermion Varia 2.6.218
		fiber: fiber 0.23.0-2
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flonters: Flonters 1.1.1+1.16.2
		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
		flytre_lib: FlytreLib 0.2.5
		gateofbabylon: Gate Of Babylon 1.2.1-1.16.2
		givemehats: Give Me Hats! 1.4
		glassdoor: Glass Doors 1.5.0-1.16
		glassential: Glassential 1.16.4-1.1.5
		go-fish: Go Fish 1.2.1-beta-1.16.4
		golemsgalore: Golems Galore 0.2.0+mc.1.16.2
		goml: Get Off My Lawn 1.3.2-beta
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		hard-hat-steve: Hard Hat Steve 1.2.0
		hardcorequesting: Hardcore Questing Mode 1.16.2+5.5.6
		harvest: Harvest 1.2.12
		harvest_scythes: Harvest Scythes 1.0.9
		hctm-base: HCTM Base 3.5.1
		horseinfo: Horse Info 0.2.2-1.16.1
		ignis-fatuus: Ignis Fatuus 1.1.3
		improved-stations: Improved Stations 2.0.3
		indrev: Industrial Revolution 1.8.4-BETA
		inmis: Inmis 2.1.1-1.16.4
		inventorysorter: Inventory Sorter 1.7.7-1.16
		invtrashslot: InvTrashSlot 1.0.2
		iron-jetpacks: Iron Jetpacks 0.2.5
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		javax_vecmath_vecmath: vecmath 1.5.2
		jumploader: Jumploader 2.1.2
		kibe: Kibe 1.6.3-BETA
		ktdatataglib: KtDataTagLib 1.4.0
		kubejs: KubeJS 1605.3.6-build.168
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lapisreserve: Lapis Reserve 1.0.6
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		library_of_exile: Library of Exile 1.0.6
		libstructure: LibStructure 1.5
		lightstones: Lightstones 1.3.0
		lithium: Lithium 0.6.3
		magna: Magna 1.4.3-1.16.2
		mcdict: MCDict 2.0.1+1.16.4
		megane: megane 3.1.3+1.16.5
		megane-api: megane-api 3.1.3+1.16.5
		megane-impl: megane-impl 3.1.3+1.16.5
		megane-runtime: megane-runtime 3.1.3+1.16.5
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		mo_glass: Mo Glass 1.5-MC1.16.5
		modern_industrialization: Modern Industrialization 0.3.12
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		multi_item_lib: Multi Item Lib 1.1.1
		netherite_plus: Netherite Plus Mod 1.3.17-1.16.5
		nourish: Nourish 1.2.1
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		oro_config: OroArmor Config 1.2.0
		packages: Packages 1.1.1
		patchouli: Patchouli 1.16.4-50-FABRIC
		phosphor: Phosphor 0.7.1+build.11
		player_roles: Player Roles 1.3.0
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.7-1.16.4
		qcommon-cfg-core: qcommon-cfg-core 3.2.0
		qcommon-croco: Croco 2.1.1
		quickshulker: Quick Shulker 1.1.14-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.7.1+build.129
		repurposed_structures: Repurposed Structures 1.16.5-1.8.1
		reroll: Reroll 1.2.0-1.16.5
		respawnablepets: Respawnable Pets 1.16.5-1
		rhino: Rhino 1.7.13-build.14
		riverredux: River Redux 0.1.6
		roughlyenoughitems: Roughly Enough Items 5.10.181
		roughlyenoughitems-api: REI (API) 5.10.181
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.181
		roughlyenoughitems-runtime: REI (Runtime) 5.10.181
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		rswires: RSWires 4.10.2
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		runelic: Runelic 1.0.2
		sandwichable: Sandwichable 1.2-beta5
		savemystronghold: Save My Stronghold! 1.16.4-1.0
		secretrooms: Secret Rooms 0.9.3+1.16.5
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		shulkerutils: shulkerutils 1.0.1-1.16
		simpleteleporters: Simple Teleporters 2.2.1
		simplexterrain: Simplex Terrain 0.7.2
		smootherbedrock: Smoother Bedrock 1.0.0
		someforgepatchesported: Some Forge Patches Ported 1.0.0
		special-circumstances: Special Circumstances 1.8.218
		staffofbuilding: Staff of Building 1.2.5-1.16.5
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		strawdummy: Straw Dummy 1.4.0
		structure-helpers: Structure Helpers 3.0.0
		structurized: Structurized 1.1.0
		survivalisland: Survival Island 0.1.5
		tacocraft: TacoCraft 1.3.1+mc.1.16
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.0+build.205
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		tis3d: TIS-3D 1.6.1
		tis3d-additions: TIS-3D Additions 0.2.1+1.16.2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		totemmod: Wither Totems Mod 0.3.2
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.3.1
		trinkets: Trinkets 2.6.7
		truerooms: True Secret Rooms 1.1.3
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		vanillaexcavators: Vanilla Excavators 1.1.0
		villagerhats: Villager Hats fabric-1.16.4-1.0.1
		voyager: Voyager 1.0.0
		waystones: Waystones 1.1.1.1
		wild_explorer: Wild Explorer 1.3.2
		winged: Winged Mod 1.16.2-1.4.1
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		woodenhoppers: Wooden Hoppers 1.0.0
		woods_and_mires: Woods and Mires 1.0.4+1.16.3
		wthit: wthit 2.2.1+1.16.5
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.16.4-Fabric-1
	Player Count: 2 / 5; [class_3222['Tronto1899'/37500, l='ServerLevel[world]', x=-252.19, y=71.00, z=-34.04], class_3222['cavayero'/79429, l='ServerLevel[world]', x=-251.27, y=71.00, z=-35.52]]
	Data Packs: vanilla (incompatible), Fabric Mods, null
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by szumaster** [comment]
the problem was successfully solved: I check two options, both solve the issue: Update modpack to 2.6.8/9 or just single upgrade VanillaDeathChest to version 2.0.5.
