### ISSUE TITLE
My worlds are no longer accessible

### ISSUE THREAD

**Issue by ShyAndSleepy** [TeamAOF/All-of-Fabric-3#308]
Whenever i try to load my worlds it crashes and i dont know why

here's the crash logs

java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
    at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
    at hardcorequesting.common.fabric.quests.QuestingDataManager$State.loadFromString(QuestingDataManager.java:129)
    at hardcorequesting.common.fabric.quests.SimpleSerializable$$Lambda$4753/258905209.accept(Unknown Source)
    at java.util.Optional.ifPresent(Optional.java:159)
    at hardcorequesting.common.fabric.quests.SimpleSerializable.load(SimpleSerializable.java:36)
    at hardcorequesting.common.fabric.quests.QuestLine.loadAll(QuestLine.java:185)
    at hardcorequesting.common.fabric.event.WorldEventListener.onLoad(WorldEventListener.java:18)
    at hardcorequesting.common.fabric.HardcoreQuestingCore$$Lambda$4836/112001548.accept(Unknown Source)
    at hardcorequesting.fabric.HardcoreQuestingFabric$$Lambda$4839/1810652856.onLoad(Unknown Source)
    at net.minecraft.class_3218.handler$bbg000$init(class_3218.java:4592)
    at net.minecraft.class_3218.<init>(class_3218.java:213)
    at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:368)
    at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:335)
    at net.minecraft.class_1132.method_3823(class_1132.java:67)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
    at net.minecraft.server.MinecraftServer$$Lambda$10402/1739571934.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)

**Comment by ProjectET** [comment]
go to your save folder, and find and delete the hqm folder.

**Comment by Monster-Zer0** [comment]
no response from op. Closing issue
