### ISSUE TITLE
Unable to perform /reload

### ISSUE THREAD

**Issue by WangJiangJiaoZi** [TeamAOF/All-of-Fabric-3#349]
version : 2.7.2
java: 1.8.0_101

```shell
reload
[17:08:44] [Server thread/INFO]: Reloading!
[17:08:44] [Server thread/INFO]: [megane] Loaded Config.
[17:08:44] [Server thread/WARN]: Failed to execute reload
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Class moriyashiine.bewitchment.common.registry.BWCommands$FortuneArgumentType already has a serializer!
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:991) ~[?:1.8.0_101]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_101]
        at net.minecraft.server.MinecraftServer.method_29439(MinecraftServer.java:1326) ~[intermediary-server.jar:?]
        at net.minecraft.class_3097.method_29480(class_3097.java:22) ~[intermediary-server.jar:?]
        at net.minecraft.class_3097.method_13530(class_3097.java:53) ~[intermediary-server.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[intermediary-server.jar:?]
        at net.minecraft.class_2170.redirect$zbm000$performCommand(class_2170.java:549) ~[intermediary-server.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:249) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_13941(class_3176.java:340) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:313) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: Class moriyashiine.bewitchment.common.registry.BWCommands$FortuneArgumentType already has a serializer!
        at net.minecraft.class_2316.method_10017(class_2316.java:74) ~[intermediary-server.jar:?]
        at moriyashiine.bewitchment.common.registry.BWCommands.init(BWCommands.java:39) ~[bewitchment-1.16.5-8.jar:?]
        at net.fabricmc.fabric.api.command.v1.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:41) ~[0cdfe522-c4f0-4539-905d-98bb697a8400.jar:?]
        at net.minecraft.class_2170.handler$zei000$fabric_addCommands(class_2170.java:1047) ~[intermediary-server.jar:?]
        at net.minecraft.class_2170.<init>(class_2170.java:233) ~[intermediary-server.jar:?]
        at net.minecraft.class_5350.<init>(class_5350.java:34) ~[intermediary-server.jar:?]
        at net.minecraft.class_5350.method_29466(class_5350.java:78) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29437(MinecraftServer.java:1327) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_101]
        ... 13 more
[17:08:44] [Server thread/INFO]: Reload failed; keeping old data
```

**Comment by Monster-Zer0** [comment]
yeah, idk. we have same issue. have not been able to figure out.

**Comment by dandin87** [comment]
What do you mean Monster? It tells you right there that's failing because of how Bewitchment is try to add commands, which I do not think are supposed to re-register during a reload

**Comment by Monster-Zer0** [comment]
imma fight you.

**Comment by Monster-Zer0** [comment]
https://github.com/MoriyaShiine/bewitchment/issues/120

**Comment by Monster-Zer0** [comment]
fixed in a commit for bewitchment https://github.com/MoriyaShiine/bewitchment/commit/b4dc3c3e0ca4f5fc4ae234827cc5a74ea6fdd09a
