### ISSUE TITLE
[BUG]Player Login Abnormal

### ISSUE THREAD

**Issue by WangJiangJiaoZi** [TeamAOF/All-of-Fabric-3#365]
**Is this a modpack or mod issue?**
(if something is screwy using a certain mod, then send the bug to the mod dev first.)

**PLEASE MENTION IF YOU ADDED ANY MODS.. ESPECIALLY SODIUM, IF YOU DON'T, IT MAKES US VERY GRUMPY**

**Modpack Version**
2.7.2

**Describe the bug**
After more players, the map will not be able to log in. Restarting also does not resolve, delete Bewitchment after the case is normal

**To Reproduce**
1.The login
2.An error
3.Log out

**Expected behavior**
Player login normally

**Logs**
```shell
[15:41:29] [Server thread/INFO]: Naipingdi joined the game
[15:41:29] [Server thread/WARN]: Failed to handle packet for /218.3.224.121:40165
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
        at net.minecraft.class_2658.<init>(class_2658.java:43) ~[intermediary-server.jar:?]
        at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.toPacket(ServerSidePacketRegistryImpl.java:61) ~[2ce42833-94a6-430c-95a9-fe8f162bdaf4.jar:?]
        at net.fabricmc.fabric.api.network.ServerSidePacketRegistry.sendToPlayer(ServerSidePacketRegistry.java:76) ~[2ce42833-94a6-430c-95a9-fe8f162bdaf4.jar:?]
        at net.fabricmc.fabric.api.network.ServerSidePacketRegistry.sendToPlayer(ServerSidePacketRegistry.java:97) ~[2ce42833-94a6-430c-95a9-fe8f162bdaf4.jar:?]
        at uk.me.desert_island.rer.WorldGenState.sendToPlayers(WorldGenState.java:73) ~[rer-2.1.3.jar:?]
        at net.minecraft.class_3324.handler$zig001$onPlayerConnect(class_3324.java:2465) ~[intermediary-server.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:273) ~[intermediary-server.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:113) ~[intermediary-server.jar:?]
        at net.minecraft.class_3248.redirect$dcn000$handlePlayerJoin(class_3248.java:562) ~[intermediary-server.jar:?]
        at net.minecraft.class_3248.method_18785(class_3248.java:65) ~[intermediary-server.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:228) ~[intermediary-server.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by irunatbullets** [comment]
Remove the mod `rer` from the server.

**Comment by irunatbullets** [comment]
Received a thumbs up from WangJiangJiaoZi - so I assume this is sorted.
