### ISSUE TITLE
Invalid icon for mod vanilla plus biomes

### ISSUE THREAD

**Issue by Luro02** [TeamAOF/All-of-Fabric-3#41]
```
[13:19:39] [main/ERROR]: Invalid icon for mod Vanilla Plus Biomes
java.nio.file.NoSuchFileException: 
	at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:557) ~[zipfs.jar:1.8.0_262]
	at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645) ~[zipfs.jar:1.8.0_262]
	at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278) ~[zipfs.jar:1.8.0_262]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_262]
	at io.github.prospector.modmenu.gui.ModListEntry.createIcon(ModListEntry.java:95) ~[modmenu-1.14.5+build.30.jar:?]
	at io.github.prospector.modmenu.gui.ModListEntry.bindIconTexture(ModListEntry.java:122) ~[modmenu-1.14.5+build.30.jar:?]
	at io.github.prospector.modmenu.gui.ModListEntry.method_25343(ModListEntry.java:53) ~[modmenu-1.14.5+build.30.jar:?]
	at io.github.prospector.modmenu.gui.ModListWidget.method_25311(ModListWidget.java:230) ~[modmenu-1.14.5+build.30.jar:?]
	at net.minecraft.class_350.method_25394(class_350.java:195) ~[intermediary-1.16.1.jar:?]
	at io.github.prospector.modmenu.gui.ModsScreen.method_25394(ModsScreen.java:252) ~[modmenu-1.14.5+build.30.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:603) ~[intermediary-1.16.1.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1021) ~[intermediary-1.16.1.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) ~[intermediary-1.16.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) ~[1.16.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) ~[fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) ~[fabric-loader-0.9.0+build.204.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) ~[fabric-loader-0.9.0+build.204.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171) ~[?:?]
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53) ~[?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131) ~[?:?]
	at java.util.HashMap$Values.forEach(HashMap.java:981) [?:1.8.0_262]
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by AK9Official** [comment]
Report this to the mod not here.
