### ISSUE TITLE
java.lang.NullPointerException: Container click

### ISSUE THREAD

**Issue by Luro02** [TeamAOF/All-of-Fabric-3#42]
I do not know which mod caused the crash, so I reported it to https://github.com/shedaniel/improved-stations/issues/14, because minecraft crashed, when I crafted a recipe in the crafting station, but the author told me that this is caused by a different mod, so I am reporting this here.

<details>
<summary>crash-2020-08-06_09.05.35-client.txt</summary>

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/6/20 9:05 AM
Description: Container click

java.lang.NullPointerException: Container click
	at net.minecraft.class_1856.handler$bco000$checkStackNbt(class_1856.java:526)
	at net.minecraft.class_1856.method_8093(class_1856.java:68)
	at net.minecraft.class_1869.method_8161(class_1869.java:99)
	at net.minecraft.class_1869.method_17728(class_1869.java:75)
	at net.minecraft.class_1869.method_8115(class_1869.java:24)
	at net.minecraft.class_3956.method_17725(class_3956.java:30)
	at net.minecraft.class_1863.method_17718(class_1863.java:70)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269)
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1649)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at net.minecraft.class_1863.method_8132(class_1863.java:70)
	at net.minecraft.class_1863.method_8128(class_1863.java:95)
	at net.minecraft.class_1734.method_7667(class_1734.java:59)
	at net.minecraft.class_1703.method_30010(class_1703.java:312)
	at net.minecraft.class_1703.method_7593(class_1703.java:177)
	at net.minecraft.class_636.method_2906(class_636.java:399)
	at net.minecraft.class_465.method_2383(class_465.java:562)
	at net.minecraft.class_465.method_25402(class_465.java:358)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1041)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1856.handler$bco000$checkStackNbt(class_1856.java:526)
	at net.minecraft.class_1856.method_8093(class_1856.java:68)
	at net.minecraft.class_1869.method_8161(class_1869.java:99)
	at net.minecraft.class_1869.method_17728(class_1869.java:75)
	at net.minecraft.class_1869.method_8115(class_1869.java:24)
	at net.minecraft.class_3956.method_17725(class_3956.java:30)
	at net.minecraft.class_1863.method_17718(class_1863.java:70)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269)
	at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1649)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at net.minecraft.class_1863.method_8132(class_1863.java:70)
	at net.minecraft.class_1863.method_8128(class_1863.java:95)
	at net.minecraft.class_1734.method_7667(class_1734.java:59)
	at net.minecraft.class_1703.method_30010(class_1703.java:312)

-- Click info --
Details:
	Menu Type: <no type>
	Menu Class: me.shedaniel.istations.containers.CraftingStationScreenHandler
	Slot Count: 46
	Slot: 0
	Button: 0
	Type: PICKUP
Stacktrace:
	at net.minecraft.class_1703.method_7593(class_1703.java:177)
	at net.minecraft.class_636.method_2906(class_636.java:399)
	at net.minecraft.class_465.method_2383(class_465.java:562)
	at net.minecraft.class_465.method_25402(class_465.java:358)
	at net.minecraft.class_312.method_1611(class_312.java:92)

-- Affected screen --
Details:
	Screen name: me.shedaniel.istations.containers.CraftingStationScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)

-- Affected level --
Details:
	All players: 1 total; [class_746['Luroalive'/71861, l='ClientLevel', x=99.97, y=75.00, z=12.54]]
	Chunk stats: Client Chunk Cache: 729, 482
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,79,64), Chunk: (at 0,4,0 in 7,4; contains blocks 112,0,64 to 127,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 18499406 game time, 702454 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:672)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 5.7.12-arch1-1
	Java Version: 1.8.0_262, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 288904576 bytes (275 MB) / 2015363072 bytes (1922 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms1024m -Xmx8192m
	Fabric Mods: 
		adabraniummod: Adabranium Mod 1.1.5.1
		adorn: Adorn 1.9.1+1.16.1
		advancements-enlarger: Advancements Enlarger 0.2.2
		adventurez: AdventureZ 1.0.7
		amecsapi: Amecs API 1.0.2+1.16-rc1
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		appleskin: AppleSkin 1.0.11
		artifice: Artifice 0.8.0+1.16-rc1
		astromine: Astromine 1.4.3
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		bambootweaks: Bamboo Tweaks unspecified
		bebooks: Better Enchanted Books 1.1.1
		bettergraves: Better Graves 0.3.0
		blockmeter: Block Meter 1.16-fabric0.13.1-1.4.3
		blockus: Blockus 1.6.2
		blue_endless_jankson: jankson +
		boringbackgrounds: Boring Backgrounds 2.1.0-1.16.pre3
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		campanion: Campanion 1.1.13+build.35
		cardinal-components: Cardinal Components API 2.4.2
		cardinal-components-base: Cardinal Components API (base) 2.4.2
		cardinal-components-block: Cardinal Components API (blocks) 2.4.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.4.2
		cardinal-components-entity: Cardinal Components API (entities) 2.4.2
		cardinal-components-item: Cardinal Components API (items) 2.4.2
		cardinal-components-level: Cardinal Components API (world saves) 2.4.2
		cardinal-components-util: Cardinal Components API (utilities) 2.4.2
		cardinal-components-world: Cardinal Components API (worlds) 2.4.2
		cavebiomes: Cave Biomes 0.2.4
		chainmail: Chainmail 0.3.0
		cherishedworlds: Cherished Worlds 1.0.1-1.16.1
		chunkpregen: Fabric Chunk Pregenerator 0.2.2
		cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.0.7
		cloth-armor-api-v1: Cloth Armor API v1 1.0.7
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.7
		cloth-common-events-v1: Cloth Common Events v1 1.0.7
		cloth-config2: Cloth Config v4 4.6.0
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.0.7
		cloth-scissors-api-v1: Cloth Scissors API v1 1.0.7
		cloth-utils-v1: Cloth Utils v1 1.0.7
		coderecipes: Programmatic Recipes 0.3.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compactstatuseffects: Compact Status Effects 1.2.0
		compressedblocks: Compressed Blocks 1.0
		controlling: Controlling For Fabric 1.1.2
		cotton: Cotton 1.0.5
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.5
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		couplings: Couplings 1.3.1
		craftpresence: CraftPresence 1.6.6
		creativebuttonmover: Creative Button Mover 0.2.5
		crookedcrooks: Crooked Crooks 1.2.1+1.16.1
		crusade: Crudade Mod 1.1.2
		diggusmaximus: Diggus Maximus 1.3.0-1.16
		dishes: Delicious Dishes 1.0.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.1.3-beta
		dynamicfps: Dynamic FPS 1.1.4
		dynocaps: DynoCaps 1.1.1
		ecotones: Ecotones 0.5.1
		eggtab: Egg Tab 1.2.0+1.16-fabric
		endreborn: End: Rebellion 1.5
		expandedstorage: ExpandedStorage 5.3.16
		experimentaway: ExperimentAway 1.0.0
		ezpas: Ezpas 1.0.4
		fabric: Fabric API 0.16.2+build.385-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474cb0
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-diagonal-panes: Fabric Diagonal Panes 0.3.0
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030fb0
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-furnaces: Fabric Furnaces 1.3.1-1.16.1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c5b0
		fabric-language-kotlin: Fabric Language Kotlin 1.3.71+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		fatxporbs: Fat Experience Orbs 0.0.7
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-1
		flesh2leather: Flesh2Leather 1.0.0
		flonters: Flonters 1.1.0+1.16.1
		flora-doubling: Flora Doubling 1.1.2
		gameinfo: GameInfo 2.0.0a-experimental-06 1.16.1
		gbfabrictools: GBfabrictools 1.2.2+1.16
		givemehats: Give Me Hats! 1.2.8
		glassdoor: Glass Doors 1.4.4-1.16
		glassential: Glassential 1.16.1-1.1.4
		golemsgalore: Golems Galore 0.1.4+mc.1.16.1
		hard-hat-steve: Hard Hat Steve 1.1.1
		harvest: Harvest 1.2.12
		healthoverlay: Health Overlay 3.6.12
		horseinfo: Horse Info 0.2.2-1.16.1
		identity: Identity 1.5.1-beta-1.16.1
		iknowwhatimdoing: I Know What I'm Doing 3.0.0
		improved-stations: Improved Stations 2.0.2-unstable
		indrev: Industrial Revolution 1.4.7-BETA
		inmis: Inmis 1.2.0-1.16.1
		intotheomega: Into the Omega 1.0.1-beta-1.16.1
		inventorysorter: Inventory Sorter 1.7.0-1.16
		iron-jetpacks: Iron Jetpacks 0.2.5
		jankson: Jankson 3.0.0+j1.2.0
		jumploader: Jumploader 2.0.0
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.1.12-BETA
		kubejs: KubeJS 1.1.2
		kyrptconfig: Kytpt Config 1.1.0-1.16
		libblockattributes_core: LibBlockAttributes (Core) 0.7.1-pre.4
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.7.1-pre.4
		libblockattributes_items: LibBlockAttributes (Items) 0.7.1-pre.4
		libcd: LibCapableData 2.5.0+1.16.1
		libgui: LibGui 2.2.0+1.16.1
		libstructure: Libstructure 1.3
		lightoverlay: Light Overlay 5.4.1
		linkart: Linkart unspecified
		linkedstorage: Linked Storage 1.3.5-1.16
		lithium: Lithium 0.5.1
		lvmnt: SuperAxes 1.1.4
		magna: Magna 1.2.0-1.16.1
		mambience: MAmbience 2.1.0-1.16
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0
		mo_glass: Mo Glass 1.3-MC1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		moreberries: More Berries 1.3.1
		morepaths: More Paths 0.0.2
		mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
		mousewheelie: Mouse Wheelie 1.5.0+mc1.16.1
		netheritehorsearmor: Netherite Horse Armor 0.3.3
		ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.5
		notes: Notes 1.0.1
		okzoomer: Ok Zoomer 4.0.0-alpha.5+1.16.1
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.71
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.71
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.5
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.5
		p3utils: P3NG00's Utilities 0.0.0
		packages: Packages 1.0
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16-38-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		piglintag: PiglinTag 1.0.0
		playerabilitylib: Pal 1.2.0
		quickshulker: Quick Shulker 1.1.5-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.3.4+build.64
		repurposed_structures: Repurposed Structures 1.3.2
		respawnablepets: Respawnable Pets r3
		ringsofascension: Rings of Ascension 1.0.4
		riverredux: River Redux 0.1.4
		roughlyenoughitems: Roughly Enough Items 4.10.4
		roughlyenoughresources: Roughly Enough Resources 2.0.2
		sandwichable: Sandwichable 1.1.1-snapshot
		secretrooms: Secret Rooms 0.9.1+1.16.1
		shapes: Shapes 2.0.0+build.10
		shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
		simpledrawers: Simple Drawers 1.8.0-1.16.1
		simpleteleporters: Simple Teleporters 2.2.0
		simplevoidworld: Simple Void World 4.0.0
		simplexterrain: Simplex Terrain 0.6.5
		slabhelper: Slab Helper 1.3.1
		slight-gui-modifications: 'Slight' GUI Modifications 1.2.0
		slotlink: slotlink 1.0.2+minecraft-1.16.1
		smoothbedrock: Smooth Bedrock (Fabric) 1.2.3
		soulbound: Soulbound 1.0.1
		spinnery: Spinnery 3.1.13
		staffofbuilding: Staff of Building 1.2.0-1.16
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		structurized: Structurized 1.0.0
		survivalisland: Survival Island 0.1.5
		tacocraft: TacoCraft 1.3.1+mc.1.16
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.4.5+build.88
		terraform: Terraform 2.1.7+build.31
		terrestria: Terrestria 2.0.4+build.50
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 2.2.14+build.28
		trinkets: Trinkets 2.6.3
		tweed: Tweed API 3.0.0-beta.9
		universalcomponents: Universal Components 0.7.2+1.16-pre2
		vanilla-hammers: Vanilla Hammers 2.0.3-1.16.1
		vanillaexcavators: Vanilla Excavators 1.1.0
		vanillaplusbiomes: Vanilla Plus Biomes 0.2.2
		villagerhats: Villager Hats fabric-1.16-rc1-1.0.0
		waila: Hwyla 1.9.22
		winged: Winged Mod 1.16-1.2
		wolveswitharmor: Wolves With Armor 1.4.0-1.16.1
		woods_and_mires: Woods and Mires 1.0.0+1.16.1
		wrenchable: Wrenchable 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 20.18.0
		xaeroworldmap: Xaero's World Map 1.8.0
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 965M/PCIe/SSE2 GL version 4.6.0 NVIDIA 450.57, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, slightguimodifications:cts_textures, secretrooms:client_pack, kubejs:resource_pack, virtual/fabric-diagonal-panes:models, file/Sildurs fabulous shaders v1.0.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
```
</details>

**Comment by AK9Official** [comment]
How to reproduce?

**Comment by Luro02** [comment]
I am unable to reproduce it

**Comment by kaliban71** [comment]
i am getting this same error but with slot link and to recreate the crash try to make something by clicking on icon either on the left side of the right or do anything other than remove items

**Comment by kaliban71** [comment]
here is the crash logs
[crash-2020-09-02_22.10.10-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5166327/crash-2020-09-02_22.10.10-client.txt)
[crash-2020-09-02_23.00.09-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5166328/crash-2020-09-02_23.00.09-client.txt)
[crash-2020-09-02_23.02.30-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5166329/crash-2020-09-02_23.02.30-client.txt)
[crash-2020-09-02_23.23.14-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5166330/crash-2020-09-02_23.23.14-client.txt)
[crash-2020-09-02_23.50.43-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5166331/crash-2020-09-02_23.50.43-client.txt)
[crash-2020-08-30_01.52.28-client.txt](https://github.com/TeamAOF/All-of-Fabric-3/files/5166332/crash-2020-08-30_01.52.28-client.txt)

they all happened with slotlink and expanded storage for me
