### ISSUE TITLE
REI Crashes after 12 pages

### ISSUE THREAD

**Issue by SnappierSoap318** [TeamAOF/All-of-Fabric-3#99]
REI crashing after going to the 12th page of a recipe

**Comment by AK9Official** [comment]
Log would be helpful

**Comment by SnappierSoap318** [comment]
i used not enough crashes to find out that 
let me see if i can get a log

**Comment by SnappierSoap318** [comment]
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2020-09-08 16:16:35 IST
Description: Rendering screen

java.lang.NullPointerException
    at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.47)
    at uk.me.desert_island.rer.rei_stuff.EntityLootCategory.lambda$registerWidget$0(EntityLootCategory.java:56)
    at uk.me.desert_island.rer.rei_stuff.EntityLootCategory$$Lambda$8653/1729199607.render(Unknown Source)
    at me.shedaniel.rei.impl.widgets.DrawableWidget.render(DrawableWidget.java:45)
    at me.shedaniel.rei.gui.RecipeViewingScreen.render(RecipeViewingScreen.java:424)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:616)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1023)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
    at net.minecraft.client.MinecraftClient.handler$bmn000$afterCrashHandled(MinecraftClient:14344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$bmn000$afterCrashHandled(MinecraftClient:14344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
  Screen name: me.shedaniel.rei.gui.RecipeViewingScreen
  Mouse location: Scaled: (561, 65). Absolute: (1123.000000, 131.000000)
  Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000

-- Affected level --
  All players: 1 total; [class_746['RoboticHydra4'/11949, l='ClientLevel', x=29.20, y=75.00, z=13.05]]
  Chunk stats: Client Chunk Cache: 441, 240
  Level dimension: minecraft:the_nether
  Level spawn location: World: (200,78,-7), Chunk: (at 8,4,9 in 12,-1; contains blocks 192,0,-16 to 207,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Level time: 5485023 game time, 8350658 day time
  Server brand: fabric
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.16.2
  Minecraft Version ID: 1.16.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1751213840 bytes (1670 MB) / 5335154688 bytes (5088 MB) up to 5368709120 bytes (5120 MB)
  CPUs: 8
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Fabric Loader (fabricloader), REI (Runtime) (roughlyenoughitems-runtime), Roughly Enough Resources (roughlyenoughresources)
  Fabric Mods: adorn: Adorn 1.11.0+1.16.2
               advancements-enlarger: Advancements Enlarger 0.2.3
               allure: Allure 1.2.6
               amecsapi: Amecs API 1.0.2+mc1.16-rc1
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               appleskin: AppleSkin 1.0.11
               appliedenergistics2: Applied Energistics 2 8.1.0-alpha.7
               artifice: Artifice 0.13.1+1.16.2-rc1
               astromine: Astromine 1.9.2+fabric-1.16.2
               astromine-core: Astromine: Core 1.9.2+fabric-1.16.2
               astromine-discoveries: Astromine: Discoveries 1.9.2+fabric-1.16.2
               astromine-foundations: Astromine: Foundations 1.9.2+fabric-1.16.2
               astromine-technologies: Astromine: Technologies 1.9.2+fabric-1.16.2
               astromine-transportations: Astromine: Transportations 1.9.2+fabric-1.16.2
               autoconfig1u: Auto Config v1 Updated 3.2.2
               bambootweaks: Bamboo Tweaks unspecified
               bebooks: Better Enchanted Books 1.1.1
               bedspreads: Bedspreads 1.1.0-1.16.2
               blade: Blade 1.0.1
               blockus: Blockus 1.6.3.2
               blue_endless_jankson: jankson +
               boringbackgrounds: Boring Backgrounds 2.1.0-1.16.pre3
               byg: BYG 1.0.6
               campanion: Campanion 1.2.0+build.39
               can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
               cardinal-components-base: Cardinal Components API (base) 2.5.4
               cardinal-components-block: Cardinal Components API (blocks) 2.5.4
               cardinal-components-chunk: Cardinal Components API (chunks) 2.5.4
               cardinal-components-entity: Cardinal Components API (entities) 2.5.4
               cardinal-components-item: Cardinal Components API (items) 2.5.4
               cardinal-components-level: Cardinal Components API (world saves) 2.5.4
               cardinal-components-util: Cardinal Components API (utilities) 2.5.4
               cardinal-components-world: Cardinal Components API (worlds) 2.5.4
               cavebiomes: Cave Biomes 0.3.0
               ce_foodstuffs: Common Expansion: Foodstuffs 1.0.1
               chainmail: Chainmail 0.5.0
               cherishedworlds: Cherished Worlds 1.1.0-1.16.2
               chunkpregen: Fabric Chunk Pregenerator 0.2.2
               cleancut: CleanCut mc1.16-2.1-fabric
               cloth-api: Cloth API 1.4.6
               cloth-armor-api-v1: Cloth Armor API v1 1.4.6
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.6
               cloth-common-events-v1: Cloth Common Events v1 1.4.6
               cloth-config2: Cloth Config v4 4.8.1
               cloth-datagen-api-v1: Cloth Datagen v1 1.4.6
               cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.6
               cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.6
               cloth-scissors-api-v1: Cloth Scissors API v1 1.4.6
               cloth-utils-v1: Cloth Utils v1 1.4.6
               com_electronwill_night-config_core: core 3.6.0
               com_electronwill_night-config_toml: toml 3.6.0
               com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
               com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
               com_moandjiezana_toml_toml4j: toml4j 0.7.2
               compressedblocks: Compressed Blocks 1.0
               controlling: Controlling For Fabric 1.1.2
               cotton: Cotton 1.0.7
               cotton-cauldron: Cotton Cauldron 1.0.4
               cotton-commons: Cotton Commons 1.0.4
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-datapack: Cotton Datapack 1.0.7
               cotton-logging: Cotton Logging 1.0.0-rc.4
               cotton-player-events: Cotton Player Events 1.0.2
               couplings: Couplings 1.3.1
               craftpresence: CraftPresence 1.6.8
               crawl: Crawl 0.7.3
               crookedcrooks: Crooked Crooks 1.2.1+1.16.1
               crusade: Crusade 1.1.4+1.16.2
               dankstorage: Dank Storage 1.6a-1.16.2
               diggusmaximus: Diggus Maximus 1.3.1-1.16
               disablecustomworldsadvice: Disable Custom Worlds Advice 1.0
               dml-refabricated: Deep Mob Learning: Refabricated 0.3.1-beta1
               dwarfcoal: Dwarf Coal 1.16.2-1.0.0
               dynamicfps: Dynamic FPS 1.2.1
               eggtab: Egg Tab 1.3.0+1.16-fabric
               endreborn: End: Rebellion 1.8
               exotic-art-core: Exotic Art Core Content Pack 1.0.358
               exotic-art-tech: Exotic Art Tech Pack 1.2.358
               exotic-matter: Exotic Matter 2.10.358
               expandedstorage: ExpandedStorage 5.6.26
               ezpas: Ezpas 1.2.1-1.16.2
               fabric: Fabric API 0.20.1+build.401-1.16
               fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
               fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
               fabric-diagonal-panes: Fabric Diagonal Panes 0.3.1
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
               fabric-furnaces: Fabric Furnaces 1.3.2-1.16.2
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
               fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1884e
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.7.0+432ea1884e
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea1884e
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e4e
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.5+fcdfdfa14e
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.0+8bcfced84e
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.0+8bcfced84e
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.11+fb0d9b0e4e
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.0+432ea1884e
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf4e
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
               fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e4e
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
               fabricloader: Fabric Loader 0.9.2+build.206
               facility: Facility 0.11.184
               fallflyinglib: FallFlyingLib 1.1.0
               fatxporbs: Fat Experience Orbs 0.0.7
               fermion: Fermion 2.5.201
               fermion-gui: Fermion GUI 2.4.201
               fermion-modkeys: Fermion Modifier Keys 1.9.201
               fermion-orientation: Fermion Orientation 1.1.201
               fermion-simulator: Fermion Simulator 1.7.201
               fermion-varia: Fermion Varia 2.3.201
               fiber: fiber 0.23.0-2
               flesh2leather: Flesh2Leather 1.0.1
               flonters: Flonters 1.1.1+1.16.2
               flora-doubling: Flora Doubling 1.1.2
               fluidity: Fluidity 0.15.192
               fonthack: Font Hack 2.3.41
               gameinfo: GameInfo 2.0.0a-experimental-06.1 1.16.2
               givemehats: Give Me Hats! 1.2.8
               glassdoor: Glass Doors 1.4.4-1.16
               glassential: Glassential 1.16.1-1.1.4
               goml: Get Off My Lawn 1.1.0
               hard-hat-steve: Hard Hat Steve 1.1.1
               hardcorequesting: Hardcore Questing Mode 0.2.3
               harvest: Harvest 1.2.12
               hctm-base: HCTM Base 3.4.0
               healthoverlay: Health Overlay 3.6.12
               horseinfo: Horse Info 0.2.2-1.16.1
               iknowwhatimdoing: I Know What I'm Doing 3.0.0
               improved-stations: Improved Stations 2.0.3
               indrev: Industrial Revolution 1.6.6-BETA
               inmis: Inmis 1.3.0-1.16.2
               inventorysorter: Inventory Sorter 1.7.2-1.16
               iron-jetpacks: Iron Jetpacks 0.2.5
               jankson: Jankson 3.0.1+j1.2.0
               jumploader: Jumploader 2.0.1
               jumpoverfences: JumpOverFences 1.16-0.0.3
               kibe: Kibe 1.3.3-BETA
               ktdatataglib: KtDataTagLib 1.4.0
               kubejs: KubeJS 1.4.5
               kyrptconfig: Kytpt Config 1.1.2-1.16
               lapisreserve: Lapis Reserve 1.0.6
               libaddict: libaddict 0.2.1
               libblockattributes_core: LibBlockAttributes (Core) 0.8.2-pre.1
               libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.2-pre.1
               libblockattributes_items: LibBlockAttributes (Items) 0.8.2-pre.1
               libcd: LibCapableData 2.5.0+1.16.2
               libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
               libstructure: LibStructure 1.5
               lightoverlay: Light Overlay 5.5.2
               linkart: Linkart unspecified
               linkedstorage: Linked Storage 1.3.7-1.16
               lithium: Lithium 0.5.4
               loadcatcher: Entrypoint Catcher 2.0.0
               magna: Magna 1.4.0-1.16.2
               mambience: MAmbience 2.1.0+1.16.2
               maybe-data: Maybe data 1.0.0-1.16.2
               minecraft: Minecraft 1.16.2
               mm: Manningham Mills 2.1
               modmenu: Mod Menu 1.14.6+build.31
               mousewheelie: Mouse Wheelie 1.5.3+mc1.16.2-pre1
               no-potion-offset: No Potion Offset 1.0.1-unstable
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               okzoomer: Ok Zoomer 4.0.1+1.16.2
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               org_joml_joml: joml 1.9.25
               packages: Packages 1.1
               parchment: Parchment 1.0.2+1.15.2
               patchouli: Patchouli 1.16-40-FABRIC
               phosphor: Phosphor 0.6.0+build.7
               playerabilitylib: Pal 1.2.1
               pling: Pling 1.2.0
               qcommon-cfg-core: qcommon-cfg-core 3.2.0
               qcommon-croco: Croco 2.1.1
               quickshulker: Quick Shulker 1.1.6-1.16
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               reborncore: Reborn Core 4.4.1+build.69
               repurposed_structures: Repurposed Structures 1.16.2-1.5.3
               respawnablepets: Respawnable Pets 6
               rgbable: RGBable 1.0.0
               ringsofascension: Rings of Ascension 1.0.7
               roughlyenoughitems: Roughly Enough Items 5.2.10
               roughlyenoughitems-api: REI (API) 5.2.10
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.2.10
               roughlyenoughitems-runtime: REI (Runtime) 5.2.10
               roughlyenoughresources: Roughly Enough Resources 2.1.0
               rswires: RSWires 4.9.1
               rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
               sandwichable: Sandwichable 1.1.2
               secretrooms: Secret Rooms 0.9.2+1.16.2
               shapes: Shapes 2.0.0+build.10
               shulkerboxtooltip: Shulker Box Tootip 2.1.1+1.16.2
               simpleteleporters: Simple Teleporters 2.2.1
               slabhelper: Slab Helper 1.3.3
               slight-gui-modifications: 'Slight' GUI Modifications 1.3.0
               smootherbedrock: Smoother Bedrock 1.0.0
               special-circumstances: Special Circumstances 1.7.201
               staffofbuilding: Staff of Building 1.2.2-1.16.2
               static-content: Static Content 1.0.1-1.16.2
               staticdata: Static Data 1.1.2
               stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
               structure-helpers: Structure Helpers 3.0.0
               tacocraft: TacoCraft 1.3.1+mc.1.16
               team_reborn_energy: Energy 0.1.0
               techreborn: Tech Reborn 3.5.2+build.110
               tis3d: TIS-3D 1.5.0
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               trapexpansion: Trap Expansion 1.3.2
               trinkets: Trinkets 2.6.4
               tweed: Tweed API 3.0.0-beta.13
               universalcomponents: Universal Components 0.7.3+1.16.2
               vanilla-hammers: Vanilla Hammers 2.0.6-1.16.2
               vanilladeathchest: VanillaDeathChest 1.16.2-1.11.0.6-fabric
               vanillaexcavators: Vanilla Excavators 1.1.0
               villagerhats: Villager Hats fabric-1.16-rc1-1.0.0
               waila: Hwyla 1.9.22
               winged: Winged Mod 1.16.2-1.4.0
               wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
               wrenchable: Wrenchable 1.0.0+1.16.1
               xaerominimap: Xaero's Minimap 20.20.3
               xaeroworldmap: Xaero's World Map 1.10.3
               xpstorage: XP Storage 0.4.1+1.16.2
               yosbr: YOSBR 0.1.1
  Patchouli open book context: n/a
  Launched Version: fabric-loader-0.9.2+build.206-1.16.2
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: fabric/fermion, fabric/fallflyinglib, fabric/crusade, fabric/ezpas, fabric/fermion-orientation, fabric/fabricloader, fabric/trinkets, fabric/fermion-gui, fabric/fabric-game-rule-api-v1, fabric/fermion-modkeys, fabric/fabric-api-base, fabric/astromine-discoveries, fabric/special-circumstances, fabric/fonthack, fabric/packages, fabric/ce_foodstuffs, fabric/astromine-transportations, fabric/playerabilitylib, fabric/waila, fabric/astromine-foundations, fabric/villagerhats, fabric/fabric-diagonal-panes, fabric/fabric-networking-v0, fabric/pling, fabric/techreborn, fabric/cleancut, fabric/repurposed_structures, fabric/modmenu, fabric/phosphor, fabric/roughlyenoughitems-runtime, fabric/structure-helpers, fabric/fabric-crash-report-info-v1, fabric/fabric-key-binding-api-v1, fabric/trapexpansion, fabric/universalcomponents, fabric/libblockattributes_fluids, fabric/magna, fabric/staticdata, fabric/adorn, fabric/exotic-matter, fabric/rgbable, fabric/parchment, fabric/dwarfcoal, fabric/linkedstorage, fabric/mambience, fabric/vanillaexcavators, fabric/lithium, fabric/fabric-object-builder-api-v1, fabric/hctm-base, fabric/ringsofascension, fabric/hardcorequesting, fabric/fabric-rendering-data-attachment-v1, fabric/wolveswitharmor, fabric/linkart, fabric/fabric-lifecycle-events-v1, fabric/fabric-loot-tables-v1, fabric/dynamicfps, fabric/goml, fabric/exotic-art-tech, fabric/libblockattributes_core, fabric/bambootweaks, fabric/compressedblocks, fabric/boringbackgrounds, fabric/xpstorage, fabric/jankson, fabric/cotton-commons, fabric/fabric-renderer-indigo, fabric/advancements-enlarger, fabric/fluidity, fabric/shapes, fabric/libgui, fabric/slight-gui-modifications, fabric/xaerominimap, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/givemehats, fabric/autoconfig1u, fabric/winged, fabric/harvest, fabric/fabric-tag-extensions-v0, fabric/inmis, fabric/can-i-mine-this-block, fabric/byg, fabric/fabric-events-lifecycle-v0, fabric/horseinfo, fabric/team_reborn_energy, fabric/fabric-keybindings-v0, fabric/no-potion-offset, fabric/artifice, fabric/stonecutter-tweaks, fabric/indrev, fabric/healthoverlay, fabric/staffofbuilding, fabric/glassential, fabric/reborncore, fabric/controlling, fabric/xaeroworldmap, fabric/diggusmaximus, fabric/roughlyenoughresources, fabric/fabric-blockrenderlayer-v1, fabric/libblockattributes_items, fabric/fabric, fabric/gameinfo, fabric/respawnablepets, fabric/dml-refabricated, fabric/wrenchable, fabric/fabric-screen-handler-api-v1, fabric/improved-stations, fabric/eggtab, fabric/tacocraft, fabric/fabric-tool-attribute-api-v1, fabric/fabric-events-interaction-v0, fabric/fabric-language-kotlin, fabric/mousewheelie, fabric/cloth-config2, fabric/fabric-resource-loader-v0, fabric/endreborn, fabric/expandedstorage, fabric/astromine-technologies, fabric/fabric-registry-sync-v0, fabric/cherishedworlds, fabric/rswires, fabric/fabric-mining-levels-v0, fabric/fabric-item-groups-v0, fabric/fabric-models-v0, fabric/shulkerboxtooltip, fabric/facility, fabric/craftpresence, fabric/fabric-renderer-api-v1, fabric/inventorysorter, fabric/flesh2leather, fabric/libcd, fabric/vanilla-hammers, fabric/cavebiomes, fabric/allure, fabric/simpleteleporters, fabric/crawl, fabric/blade, fabric/flonters, fabric/fabric-containers-v0, fabric/appliedenergistics2, fabric/mm, fabric/campanion, fabric/fabric-textures-v0, fabric/sandwichable, fabric/fabric-rendering-fluids-v1, fabric/qcommon-cfg-core, fabric/bedspreads, fabric/glassdoor, fabric/fabric-renderer-registries-v1, fabric/quickshulker, fabric/fermion-simulator, fabric/fabric-networking-blockentity-v0, fabric/okzoomer, fabric/crookedcrooks, fabric/exotic-art-core, fabric/amecsapi, fabric/cotton-datapack, fabric/fabric-item-api-v1, fabric/roughlyenoughitems, fabric/slabhelper, fabric/fabric-content-registries-v0, fabric/fabric-furnaces, fabric/vanilladeathchest, fabric/yosbr, fabric/astromine-core, fabric/fabric-object-builders-v0, fabric/secretrooms, fabric/fermion-varia
  Current Language: English (US)
  CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
  Client Crashes Since Restart: 3
  Integrated Server Crashes Since Restart: 0
```
